import { Observable } from 'rxjs';
import { TomaInventarioEntity } from '../models/toma-inventario.entity';
import { CategoriaArticuloEntity } from '../models/categoria-articulo.entity';
import { ValorizacionProductoEntity } from '../models/valorizacion-producto.entity';
import { ProductoVendidoEntity } from '../models/producto-vendido.entity';
import { StockMinimoEntity } from '../models/stock-minimo.entity';
import { StockFechaEntity } from '../models/stock-fecha.entity';
import { HistorialVencimientoEntity } from '../models/historial-vencimiento.entity';
import { DiagnosticoAlmacenEntity } from '../models/diagnostico-almacen.entity';
import { ComparacionInventarioEntity } from '../models/catalogo.entity';
import { DespachoEntity } from '../models/despacho.entity';
import { RecalculoPrecioEntity } from '../models/recalculo-precio.entity';
import { GestionDevolucionEntity } from '../models/gestion-devolucion.entity';
import { RecepcionTransferenciaEntity } from '../models/recepcion-transferencia.entity';
import { RegistroPerdidasEntity } from '../models/registro-perdidas.entity';
import { ProductoAlmacenEntity } from '../models/producto-almacen.entity';
import { ReposicionStockEntity } from '../models/reposicion-stock.entity';
import { MaestroProductoEntity } from '../models/maestro-producto.entity';
import { MovAlmacenEntity } from '../models/mov-almacen.entity';
import { ReqTrasladoEntity } from '../models/req-traslado.entity';
import { CuadreStockEntity } from '../models/cuadre-stock.entity';
import { MovimientoCuadreStockEntity } from '../models/movimiento-cuadre-stock.entity';
import { ActualizacionProductoEntity } from '../models/actualizacion-producto.entity';

export abstract class IReportesRepository {
    abstract obtenerReporteTomas(): Observable<TomaInventarioEntity[]>;
    abstract obtenerReporteValorizacion(): Observable<ValorizacionProductoEntity[]>;
    abstract obtenerReporteVendidos(): Observable<ProductoVendidoEntity[]>;
    abstract obtenerReporteStockMinimo(): Observable<StockMinimoEntity[]>;
    abstract obtenerReporteStockFecha(): Observable<StockFechaEntity[]>;
    abstract obtenerReporteHistorialVencimiento(): Observable<HistorialVencimientoEntity[]>;
    abstract obtenerReporteDiagnosticoAlmacenes(): Observable<DiagnosticoAlmacenEntity[]>;
    abstract obtenerComparacionesInventario(): Observable<ComparacionInventarioEntity[]>;
    abstract obtenerDespachos(): Observable<DespachoEntity[]>;
    abstract obtenerGestionesDevoluciones(): Observable<GestionDevolucionEntity[]>;
    abstract obtenerRecepcionesTransferencia(): Observable<RecepcionTransferenciaEntity[]>;
    abstract obtenerRegistroPerdidas(): Observable<RegistroPerdidasEntity[]>;
    abstract obtenerProductosAlmacen(): Observable<ProductoAlmacenEntity[]>;
    abstract obtenerReposicionesStock(): Observable<ReposicionStockEntity[]>;
    abstract obtenerProductosReposicionStock(): Observable<ProductoAlmacenEntity[]>;
    abstract obtenerRecalculoPrecios(): Observable<RecalculoPrecioEntity[]>;
    abstract obtenerClasificacionArticulos(): Observable<CategoriaArticuloEntity[]>;
    abstract obtenerMaestroProductos(): Observable<MaestroProductoEntity[]>;
    abstract obtenerMovAlmacenes(): Observable<MovAlmacenEntity[]>;
    abstract descargarMovimientoPdf(id: number): Observable<Blob>;
    abstract obtenerReqTraslados(): Observable<ReqTrasladoEntity[]>;
    abstract obtenerCuadreStock(): Observable<CuadreStockEntity[]>;
    abstract obtenerMovimientosCuadreStock(): Observable<MovimientoCuadreStockEntity[]>;
    abstract obtenerActualizacionProductos(): Observable<ActualizacionProductoEntity[]>;
}
