-- Trabajadores SIGRE desde MAESTRO.json (20 EMP + 20 JOR muestra planilla)
-- Filtro: FEC_CESE NULL, FLAG_ESTADO='1', FLAG_CAL_PLNLLA='1'
-- Sucursal PI=Piura, LM=Lima; cada grupo de 10: 5 ONP (COD_AFP NULL) + 5 AFP distintas
-- EMP Piura (PI): ONP=10000010, 10000016, 10000018, 20000074, 20000083 | AFP=10000009(IN), 10000001(HO), 10000003(PR), 10000004(RI), 10000006(HA)
-- EMP Lima (LM): ONP=20000374, 20000464, 20000644, 20000667, 20000668 | AFP=10000032(IN), 10000007(HO), 10000020(PR), 10000008(RI), 10000013(HA)
-- JOR Piura (PI): ONP=20000008, 20000009, 20000010, 20000014, 20000018 | AFP=20000006(IN), 20000001(HO), 20000003(PR), 20000005(RI), 20000561(HA)
-- JOR Lima (LM): ONP=20000019, 20000020, 20000029, 20000031, 20000044 | AFP=20000007(IN), 20000015(HO), 20000021(PR), 20000036(RI), 20000016(HA)
BEGIN;

INSERT INTO rrhh.trabajador (
    codigo_trabajador,
    nombres,
    nombre1,
    nombre2,
    apellido_paterno,
    apellido_materno,
    tipo_doc_identidad_id,
    numero_documento,
    fecha_nacimiento,
    sexo_id,
    estado_civil_id,
    direccion,
    telefono_fijo,
    celular1,
    celular2,
    codigo_tel_ciudad,
    email,
    flag_discapacidad,
    flag_domiciliado,
    flag_comision_afp,
    flag_pensionista,
    flag_afiliado_eps,
    flag_essalud_vida,
    flag_sctr_pension,
    flag_sctr_salud,
    flag_quinta_exonerado,
    distrito_id,
    tipo_via_id,
    nombre_via,
    numero_via,
    tipo_zona_id,
    nombre_zona,
    tipo_vivienda_id,
    interior,
    referencia,
    cuenta_bancaria_sueldo,
    cuenta_cts,
    banco_sueldo_id,
    banco_cts_id,
    moneda_sueldo_id,
    moneda_cts_id,
    admin_afp_id,
    cuspp,
    pension_rtps_id,
    regimen_pensionario_id,
    fec_ini_afil_afp,
    fec_fin_afil_afp,
    regimen_laboral_id,
    tipo_trabajador_id,
    tipo_trabajador_rtps_id,
    ocupacion_rtps_id,
    seccion_id,
    centro_costo_id,
    sucursal_id,
    nro_brevete,
    autogenerado_essalud,
    procedencia,
    comentario,
    porc_judicial,
    porc_jud_util,
    flag_cat_trab,
    flag_dscto_comedor,
    fecha_ingreso,
    fecha_cese,
    motivo_cese_id,
    flag_estado
)
VALUES
(
        '10000010',
        'MAGALY DEL PILAR',
        'MAGALY',
        'DEL PILAR',
        'VITES',
        'RODRIGUEZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '46127876',
        '1989-11-06',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'AV. REPÚBLICA DE CHILE 781 DPTO. 603',
        NULL,
        NULL,
        NULL,
        '01',
        'pilar_1689@outlook.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150113' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '193-95750288-0-60',
        '191-52410272-0-86',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        '618200DARAZ1',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '807' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8911060VERRM007',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2012-08-27',
        NULL,
        NULL,
        '1'
    ),
(
        '10000016',
        'FILIBERTO OSCAR NOLBER',
        'FILIBERTO',
        'OSCAR NOLBER',
        'RIEGA',
        'TORRES',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32963065',
        '1958-06-06',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oriegatorres@gmail.com',
        '0',
        '1',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-10013052-0-86',
        '7509048968',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '301' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010702' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        NULL,
        'LM',
        NULL,
        0,
        0,
        '2',
        '0',
        '2009-10-09',
        NULL,
        NULL,
        '1'
    ),
(
        '10000018',
        'ANGEL',
        'ANGEL',
        NULL,
        'MARTINEZ',
        'VELEZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '45036326',
        '1935-03-01',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'DIVORCIADO' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        '01',
        'angelm.cantabria@hotmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '0367335387',
        '1119081462',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM core.moneda WHERE codigo = 'US$' OR sigla_moneda = 'US$' LIMIT 1),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '806' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        NULL,
        'LM',
        NULL,
        0,
        0,
        '2',
        '0',
        '1997-01-01',
        NULL,
        NULL,
        '1'
    ),
(
        '20000074',
        'JOSE GENARO',
        'JOSE',
        'GENARO',
        'BAYONA',
        'SULLON',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '10532526',
        '1945-09-23',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'AV. MARAÑON MZ. A LT. 21 ASOCIACION PEREGRINOS DEL SEÑOR',
        NULL,
        '924826367',
        NULL,
        '01',
        'genarobayona@hotmail.com',
        '0',
        '1',
        '0',
        '1',
        '0',
        '0',
        '2',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150117' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507561780',
        '7509043209',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '12' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '5' AND s.codigo = '502' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '31020302' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '4509231BOSLJ005',
        'CH',
        NULL,
        0,
        0,
        '2',
        '0',
        '1997-01-01',
        NULL,
        NULL,
        '1'
    ),
(
        '20000083',
        'ROGER',
        'ROGER',
        NULL,
        'RAMIREZ',
        'NINAQUISPE',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '44080678',
        '1986-03-07',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'JR. RIO SANTA MZ. C LT. 4',
        NULL,
        NULL,
        NULL,
        '043',
        'ramirez.roy18@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021808' LIMIT 1),
        NULL,
        NULL,
        '592',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507439961',
        '191-46851475-0-20',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '5' AND s.codigo = '502' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '31020302' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8603071RINAR001',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2010-09-10',
        NULL,
        NULL,
        '1'
    ),
(
        '10000009',
        'DIANA VANESSA',
        'DIANA',
        'VANESSA',
        'ALVARADO',
        'RUIZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '44083156',
        '1987-02-14',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'AV SEPARADORA INDUSTRIAL MZ A  LT 31 URB. OLIMPO',
        NULL,
        NULL,
        NULL,
        '01',
        'divaru@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150103' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '0367389194',
        '0369167622',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'INTEGRA' LIMIT 1),
        '618200DARAZ1',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        (SELECT id FROM rrhh.ocupacion_rtps WHERE codigo = '251003' LIMIT 1),
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '801' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8702140AARZD003',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2012-02-01',
        NULL,
        NULL,
        '1'
    ),
(
        '10000001',
        'NERY MARYBEL',
        'NERY',
        'MARYBEL',
        'BAYONA',
        'FLORES',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '41663728',
        '1983-03-09',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'CALLE CAMILO CARRILLO 145 BLOCK B DPTO 302',
        NULL,
        NULL,
        NULL,
        '01',
        'marybelbayona@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150140' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-96964370-0-05',
        '0369153473',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HORIZONTE' LIMIT 1),
        '603820NBFOR3',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '24' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '807' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8303090BOFRN003',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-01',
        NULL,
        NULL,
        '1'
    ),
(
        '10000003',
        'JORGE EDUARDO',
        'JORGE',
        'EDUARDO',
        'YZAGA',
        'BOYER',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '08673283',
        '1968-05-02',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE TORIBIO RODRIGUEZ DE MENDOZA 215 INT 14 SAN AGUSTIN',
        NULL,
        NULL,
        NULL,
        '01',
        'jyzaga23@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150110' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-96964393-0-28',
        '310-53619657-1-18',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM core.moneda WHERE codigo = 'US$' OR sigla_moneda = 'US$' LIMIT 1),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PROFUTURO' LIMIT 1),
        '249581JIBGE9',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '804' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '6805021YGBEJ003',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2008-06-23',
        NULL,
        NULL,
        '1'
    ),
(
        '10000004',
        'MARIA ISABEL',
        'MARIA',
        'ISABEL',
        'CALDERON',
        'CUMPA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '07753347',
        '1970-01-18',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'AV BRASIL 3390 DPTO C-MAGDALENA',
        NULL,
        NULL,
        NULL,
        '01',
        'isacalde@yahoo.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '2',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150120' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-06159485-0-00',
        '310-53619656-1-08',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM core.moneda WHERE codigo = 'US$' OR sigla_moneda = 'US$' LIMIT 1),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PRIMA AFP' LIMIT 1),
        '255840MCCDP0',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '24' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '804' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7001180CDCPM001',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '1997-01-01',
        NULL,
        NULL,
        '1'
    ),
(
        '10000006',
        'RAUL ANTONIO',
        'RAUL',
        'ANTONIO',
        'VARGAS',
        'LEYVA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32732420',
        '1972-09-13',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE MANUEL FUENTES 169',
        NULL,
        NULL,
        NULL,
        '01',
        'ravl1972@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150131' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-96964383-0-18',
        '0369162649',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HABITAT' LIMIT 1),
        '565531RVLGV8',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '25' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '801' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7209131VGLVR004',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2009-10-26',
        NULL,
        NULL,
        '1'
    ),
(
        '20000374',
        'JORDAN JHONATAN',
        'JORDAN',
        'JHONATAN',
        'BURGA',
        'TERRY',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '47396846',
        '1992-03-24',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'BARRIO FISCAL # 5 MZ. C LTE. 6',
        NULL,
        '943299899',
        NULL,
        '043',
        'jburgate_2403@hotmail.com',
        '0',
        '2',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021801' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-06159466-0-74',
        '310-52740853-0-00',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '15' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '1' AND s.codigo = '104' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51010402' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2019-03-15',
        NULL,
        NULL,
        '1'
    ),
(
        '20000464',
        'ANJIEE YHOMAR',
        'ANJIEE',
        'YHOMAR',
        'CARRANZA',
        'ODOLFREDO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '47216420',
        '1992-08-10',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'JR. PACHACUTEC 266 MZ. U2 LT. 6',
        NULL,
        '998309536',
        NULL,
        '043',
        'carranzayhomar92@gmail.com',
        '0',
        '2',
        '0',
        '0',
        '0',
        '1',
        '2',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021801' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7508366221',
        '147509126350',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '1' AND s.codigo = '101' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51010402' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2022-05-01',
        NULL,
        NULL,
        '1'
    ),
(
        '20000644',
        'PEDRO ALEXIS',
        'PEDRO',
        'ALEXIS',
        'ZAVALETA',
        'ACEVEDO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '44397440',
        '1986-05-17',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'Urb. El Acero Mz A Lt 6.- Chimbote',
        NULL,
        '928881136',
        NULL,
        '043',
        'ZAVALETA_PEDRO@HOTMAIL.COM',
        '0',
        '1',
        '0',
        '0',
        '0',
        '1',
        '1',
        '0',
        '0',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '360170465357',
        '19249255192090',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '056' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '5' AND s.codigo = '502' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51010402' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2025-12-10',
        NULL,
        NULL,
        '1'
    ),
(
        '20000667',
        'PAOLA YANIRA',
        'PAOLA',
        'YANIRA',
        'CAPRISTANO',
        'BURGOS',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '75562109',
        '2004-01-18',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'URB. BELLAMAR ETAPA II MZ M4 LOTE 04',
        NULL,
        '924212954',
        NULL,
        NULL,
        'CAPRISTANOPAOLA@GMAIL.COM',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-16313759-0-36',
        NULL,
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        NULL,
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '99' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '1' AND s.codigo = '101' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51010402' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '5',
        '0',
        '2026-04-23',
        NULL,
        NULL,
        '1'
    ),
(
        '20000668',
        'VANIA CAROLINE',
        'VANIA',
        'CAROLINE',
        'CHUQUI',
        'TAPIA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '73376142',
        '2001-05-23',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'P. JOVEN SAN PEDRO MZ 67 LOTE 12',
        NULL,
        '966047609',
        NULL,
        NULL,
        'VANIACHUQUI04@GMAIL.COM',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-16075569-0-40',
        NULL,
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        NULL,
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '99' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '1' AND s.codigo = '101' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51010402' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '5',
        '0',
        '2026-04-16',
        NULL,
        NULL,
        '1'
    ),
(
        '10000032',
        'FRANCISCO ENRIQUE',
        'FRANCISCO',
        'ENRIQUE',
        'CUBA',
        'ROMERO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '07380555',
        '1964-01-29',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'CALLE MOLLOCMARCA 371 DPTO 402 URB. MARANGA',
        NULL,
        NULL,
        NULL,
        '082',
        'franciscor_cuba@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150136' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-97086267-0-34',
        '2049420330',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'INTEGRA' LIMIT 1),
        '234031FCRAE0',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '804' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '234031FCRAE0',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2016-04-01',
        NULL,
        NULL,
        '1'
    ),
(
        '10000007',
        'MAXIMO',
        'MAXIMO',
        NULL,
        'VALDIVIESO',
        'PEREA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '40056039',
        '1978-10-04',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'JR COSME BUENO 144 SALAMANCA',
        NULL,
        NULL,
        NULL,
        '01',
        'maximo@maximovp.com',
        '0',
        '1',
        '2',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150103' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '193-03702468-0-65',
        '0369163761',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HORIZONTE' LIMIT 1),
        '587651MVPDE3',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '25' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '803' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '7810041VDPEM004',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2010-01-01',
        NULL,
        NULL,
        '1'
    ),
(
        '10000020',
        'LUIS ALBERTO',
        'LUIS',
        'ALBERTO',
        'CAMPOS',
        'ESPINOZA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '15847357',
        '1975-06-20',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE MOQUEGUA S/N',
        NULL,
        NULL,
        NULL,
        '082',
        'luis.campos@cantabria.pe',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150203' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '1700549437',
        '0369705420',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM core.moneda WHERE codigo = 'US$' OR sigla_moneda = 'US$' LIMIT 1),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PROFUTURO' LIMIT 1),
        '575631LCEPI5',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '804' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        NULL,
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2008-04-16',
        NULL,
        NULL,
        '1'
    ),
(
        '10000008',
        'GERSON POOL',
        'GERSON',
        'POOL',
        'HUAMANI',
        'MENDOZA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '41675332',
        '1981-09-23',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'MZ H LOTE 07 NUEVA CAJA DE AGUA-CERCADO DE LIMA',
        NULL,
        NULL,
        NULL,
        '01',
        'dkda_20_00@hotmail.com',
        '0',
        '1',
        '2',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150101' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-05759843-0-21',
        '191-52736852-0-73',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PRIMA AFP' LIMIT 1),
        '298501GHMMD4',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '24' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '805' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '51030802' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '8109231HMMDG009',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2011-07-08',
        NULL,
        NULL,
        '1'
    ),
(
        '10000013',
        'ROSA DEL PILAR',
        'ROSA',
        'DEL PILAR',
        'RAMIREZ',
        'DEXTRE',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '07266582',
        '1972-12-16',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'F' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE MONTE SAUCE MZ H LT 06 DPTO 03 URB MONTERRICO SUR',
        NULL,
        '964560567',
        NULL,
        '01',
        'titateo@hotmail.com',
        '0',
        '1',
        '2',
        '0',
        '0',
        '0',
        '0',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '150140' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '191-97024861-0-08',
        '0369170485',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HABITAT' LIMIT 1),
        '266470RRDIT4',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '25' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'EMP' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '8' AND s.codigo = '805' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '80701002' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '7212160RIDTR004',
        'LM',
        NULL,
        0,
        0,
        '1',
        '0',
        '2013-12-16',
        NULL,
        NULL,
        '1'
    ),
(
        '20000008',
        'GUILLERMO OSWALDO',
        'GUILLERMO',
        'OSWALDO',
        'BALBIN',
        'GALLO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32769768',
        '1959-06-25',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'NUEVA ESPERANZA MZ. D LT. 15 SAN LUIS - NUEVO CHIMBOTE',
        NULL,
        NULL,
        NULL,
        '043',
        'gbalbingallo@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021809' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-09497181-0-03',
        '0369153663',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '701' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '5906251FBGLG007',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-07',
        NULL,
        NULL,
        '1'
    ),
(
        '20000009',
        'VICTOR',
        'VICTOR',
        NULL,
        'BALOIS',
        'VASQUEZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32936752',
        '1970-02-26',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'JR. ARICA - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'baloisvictor26@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '110',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507552037',
        '0369154141',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '703' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7002261BOVQV009',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2008-04-03',
        NULL,
        NULL,
        '1'
    ),
(
        '20000010',
        'JHON MARTI',
        'JHON',
        'MARTI',
        'BARRIOS',
        'VERA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '42874855',
        '1985-02-28',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'JR. SAN LUIS - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'marti_barrios85@hotmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '112',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507532260',
        '0369154125',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '701' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8502281BRVAJ003',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2007-11-19',
        NULL,
        NULL,
        '1'
    ),
(
        '20000014',
        'DOMINGO',
        'DOMINGO',
        NULL,
        'CARRANZA',
        'ALVA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32775515',
        '1958-05-13',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'JR. ATAHUALPA MZ. C-D LT. 1 AA.HH. CESAR VALLEJO',
        NULL,
        '960563407',
        NULL,
        '043',
        'domingocarranzaalva@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021801' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507651748',
        '111012341000042838',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '306' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '5805131CRAAD000',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2011-03-21',
        NULL,
        NULL,
        '1'
    ),
(
        '20000018',
        'ALFREDO MOISES',
        'ALFREDO',
        'MOISES',
        'CHERO',
        'INFANTES',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '41019369',
        '1981-06-10',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'JR. GUADALUPE - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'alfredo.chero.1022@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '145',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507574247',
        '111012341000043966',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '702' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '8106101CRIAA008',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2008-10-17',
        NULL,
        NULL,
        '1'
    ),
(
        '20000006',
        'LUIS FRANCISCO',
        'LUIS',
        'FRANCISCO',
        'AYALA',
        'CHINCHAY',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32936783',
        '1971-01-25',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'DIVORCIADO' LIMIT 1),
        'JR. PROGRESO MZ. C LT. 1',
        NULL,
        NULL,
        NULL,
        '043',
        'ayalachinchayluisfrancisco@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '100',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507665490',
        '4010339934',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '055' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'INTEGRA' LIMIT 1),
        '559561LACLN8',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '304' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7101251ALCNL008',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2011-11-17',
        NULL,
        NULL,
        '1'
    ),
(
        '20000001',
        'CESAR AUGUSTO',
        'CESAR',
        'AUGUSTO',
        'ADRIANZEN',
        'AVILA',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32948274',
        '1972-11-19',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'AV. JORGE CHAVEZ MZ. G6 LT. 24 - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'c_adrianzen@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-10016727-0-98',
        '8330900277428',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '054' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HORIZONTE' LIMIT 1),
        '566201CAAIL4',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '4' AND s.codigo = '402' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7211191AIALC007',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2007-11-15',
        NULL,
        NULL,
        '1'
    ),
(
        '20000003',
        'AMBROCIO',
        'AMBROCIO',
        NULL,
        'ALTAMIRANO',
        'PAZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32771441',
        '1961-01-08',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'UPIS DAVID DASSO HOCKEY MZ. I LT. 5',
        NULL,
        NULL,
        NULL,
        '043',
        'ambrociopazaltamirano@hotmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021809' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507653587',
        '111012341000043931',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PROFUTURO' LIMIT 1),
        '222871AAPAZ0',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '304' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '6101081AAPZA005',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-22',
        NULL,
        NULL,
        '1'
    ),
(
        '20000005',
        'JOSE MANUEL',
        'JOSE',
        'MANUEL',
        'AYALA',
        'CARRION',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '80205875',
        '1979-03-28',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'JR. PROGRESO - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'ayalacarrionjosemanuel@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '202',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507645203',
        '111012341000043982',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PRIMA AFP' LIMIT 1),
        '590931JACLR7',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '24' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '310' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        '7903281ALCRJ009',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2010-11-19',
        NULL,
        NULL,
        '1'
    ),
(
        '20000561',
        'STEVENSON',
        'STEVENSON',
        NULL,
        'BENDEZU',
        'SEBASTIAN',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '47417067',
        '1991-11-27',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'AA.HH OLLANTA HUMALA MZ. C LT. 20',
        NULL,
        '981775025',
        NULL,
        '043',
        'stevensonbendezu@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '2',
        '0',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7508533531',
        '148339015036',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HABITAT' LIMIT 1),
        '335671SBSDA5',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '25' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '2' AND s.codigo = '201' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'PI' LIMIT 1),
        NULL,
        NULL,
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2024-03-01',
        NULL,
        NULL,
        '1'
    ),
(
        '20000019',
        'HUGO HERNANDO',
        'HUGO',
        'HERNANDO',
        'CORREA',
        'AGUIRRE',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32875818',
        '1956-07-26',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'JR. ANCASH MZ. 5 LT. 10',
        NULL,
        NULL,
        NULL,
        '043',
        'hugo.correa.07@hotmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '402',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507346117',
        '0369153671',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '2' AND s.codigo = '201' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '5607261CRAIH004',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-09',
        NULL,
        NULL,
        '1'
    ),
(
        '20000020',
        'DEYBI OMAR',
        'DEYBI',
        'OMAR',
        'CRUZ',
        'GUTIERREZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '46407455',
        '1990-05-31',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'AV. 28 DE JULIO MZ. E6 LT. 11 - COISHCO',
        NULL,
        '946429685',
        NULL,
        '043',
        'deybicg@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '845',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7508103301',
        '7509111626',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '02' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '701' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '9005311CZGID005',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2009-10-12',
        NULL,
        NULL,
        '1'
    ),
(
        '20000029',
        'DOMINGO GABRIEL',
        'DOMINGO',
        'GABRIEL',
        'GUTIERREZ',
        'URBANO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32948756',
        '1962-12-20',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE EL MILAGRO MZ. C1 LT. 13A PSJ. 09',
        NULL,
        NULL,
        NULL,
        '043',
        'gutierrezurbanogabriel@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507635394',
        '7509049800',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '2' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '311' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '6212201GIUAD009',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2010-05-11',
        NULL,
        NULL,
        '1'
    ),
(
        '20000031',
        'ELIAS JOSE',
        'ELIAS',
        'JOSE',
        'HUANCA',
        'GOMEZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32804839',
        '1960-07-18',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'URB. NICOLAS GARATEA MZ. 50 LT. 14',
        NULL,
        NULL,
        NULL,
        '043',
        'joseeliashuancagomez@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021809' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7550012392',
        '0369153846',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '2' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '303' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '6007181HNGEE006',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-23',
        NULL,
        NULL,
        '1'
    ),
(
        '20000044',
        'CRISTIAN HENRY',
        'CRISTIAN',
        'HENRY',
        'OLAVARRIA',
        'GUZMAN',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32985276',
        '1977-08-15',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'AV. PANAMERICANA NORTE MZ. G LT. 2',
        NULL,
        NULL,
        NULL,
        '043',
        'cristianolavarria40@gmail.com',
        '0',
        '1',
        '0',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '122',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-10016717-0-88',
        '4010286289',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '055' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        NULL,
        NULL,
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '2' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '308' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '7708151OVGMC006',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-26',
        NULL,
        NULL,
        '1'
    ),
(
        '20000007',
        'MARIO ALBERTO',
        'MARIO',
        'ALBERTO',
        'AZAÑA',
        'LUCERO',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32936738',
        '1970-10-25',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'CALLE EL MILAGRO',
        NULL,
        NULL,
        NULL,
        '043',
        'marioazanalucero@gmail.com',
        '0',
        '1',
        '2',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '109',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-10030339-0-48',
        '111012341000042846',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'INTEGRA' LIMIT 1),
        '558641MALÑE6',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '308' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '7010250ANLEM004',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2012-05-04',
        NULL,
        NULL,
        '1'
    ),
(
        '20000015',
        'JORGE RICHARD',
        'JORGE',
        'RICHARD',
        'CARRANZA',
        'BARRIOS',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '41302834',
        '1982-06-29',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'SOLTERO' LIMIT 1),
        'PROLONGACIÓN 28 DE JULIO S/N',
        NULL,
        NULL,
        NULL,
        '043',
        'richardcarranzabarrios@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7507652266',
        '111012341000042862',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HORIZONTE' LIMIT 1),
        '601291JCBRR7',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '308' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '8206291CRBRJ006',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2011-03-31',
        NULL,
        NULL,
        '1'
    ),
(
        '20000021',
        'ALEJANDRINO CONCEPCION',
        'ALEJANDRINO',
        'CONCEPCION',
        'CRUZ',
        'OLIVARES',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32947951',
        '1958-12-05',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'JR. GONZALES PRADA MZ. D¿ LT. 17 P. JOVEN JAVIER HERAUD',
        NULL,
        '953580215',
        NULL,
        '043',
        'alejoolivares1958@gmail.com',
        '0',
        '2',
        '2',
        '0',
        '0',
        '0',
        '2',
        '2',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021808' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '310-10013773-0-14',
        '111012341000044938',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '010' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '120' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PROFUTURO' LIMIT 1),
        '515221ACOZV8',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '23' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '1' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '308' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '5812051CZOVA000',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2002-10-07',
        NULL,
        NULL,
        '1'
    ),
(
        '20000036',
        'JULIO MANUEL',
        'JULIO',
        'MANUEL',
        'MARIÑOS',
        'RAMIREZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '32543179',
        '1974-03-12',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        (SELECT id FROM rrhh.estado_civil WHERE codigo = 'CASADO' LIMIT 1),
        'CALLE EL MILAGRO MZ. M LT. 2 - COISHCO',
        NULL,
        NULL,
        NULL,
        '043',
        'Juliomanuelmr2000@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021803' LIMIT 1),
        NULL,
        NULL,
        '102',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '0630078871',
        '4010337141',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '055' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'PRIMA AFP' LIMIT 1),
        '570981JMRII7',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '24' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '7' AND s.codigo = '702' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '7403121MIRIJ000',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2007-06-05',
        NULL,
        NULL,
        '1'
    ),
(
        '20000016',
        'ANTHONY JOSE',
        'ANTHONY',
        'JOSE',
        'CASTRO',
        'JUAREZ',
        (SELECT id FROM core.tipo_doc_identidad WHERE codigo = '1' LIMIT 1),
        '42827493',
        '1985-02-18',
        (SELECT id FROM rrhh.sexo WHERE codigo = 'M' LIMIT 1),
        NULL,
        'JR. MARISCAL URETA MZ. 5 LT. 22 MIRAFLORES BAJO',
        NULL,
        NULL,
        NULL,
        '043',
        'anthonycastrojuarez@gmail.com',
        '0',
        '1',
        '1',
        '0',
        '0',
        '0',
        '0',
        '1',
        '0',
        (SELECT id FROM core.distrito WHERE codigo = '021801' LIMIT 1),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '7508060048',
        '7509050816',
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        (SELECT id FROM finanzas.banco WHERE cod_banco = '021' LIMIT 1),
        core.fn_moneda_default_pen_id(),
        core.fn_moneda_default_pen_id(),
        (SELECT id FROM rrhh.admin_afp WHERE nombre = 'HABITAT' LIMIT 1),
        '610941ACJTR1',
        (SELECT id FROM rrhh.pension_rtps WHERE codigo = '21' LIMIT 1),
        NULL,
        NULL,
        NULL,
        (SELECT id FROM rrhh.regimen_laboral WHERE codigo = '2' LIMIT 1),
        (SELECT id FROM rrhh.tipo_trabajador WHERE codigo = 'JOR' LIMIT 1),
        NULL,
        NULL,
        (SELECT s.id FROM rrhh.seccion s JOIN rrhh.area a ON a.id = s.area_id WHERE a.codigo = '3' AND s.codigo = '304' LIMIT 1),
        (SELECT id FROM contabilidad.centros_costo WHERE trim(cencos) = '21010701' LIMIT 1),
        (SELECT id FROM auth.sucursal WHERE codigo = 'LM' LIMIT 1),
        NULL,
        '8502181CTJRA004',
        'CH',
        NULL,
        0,
        0,
        '1',
        '0',
        '2011-04-02',
        NULL,
        NULL,
        '1'
    )
ON CONFLICT (codigo_trabajador) DO UPDATE SET
    nombres = EXCLUDED.nombres,
    nombre1 = EXCLUDED.nombre1,
    nombre2 = EXCLUDED.nombre2,
    apellido_paterno = EXCLUDED.apellido_paterno,
    apellido_materno = EXCLUDED.apellido_materno,
    tipo_doc_identidad_id = EXCLUDED.tipo_doc_identidad_id,
    numero_documento = EXCLUDED.numero_documento,
    fecha_nacimiento = EXCLUDED.fecha_nacimiento,
    sexo_id = EXCLUDED.sexo_id,
    estado_civil_id = EXCLUDED.estado_civil_id,
    direccion = EXCLUDED.direccion,
    telefono_fijo = EXCLUDED.telefono_fijo,
    celular1 = EXCLUDED.celular1,
    celular2 = EXCLUDED.celular2,
    codigo_tel_ciudad = EXCLUDED.codigo_tel_ciudad,
    email = EXCLUDED.email,
    flag_discapacidad = EXCLUDED.flag_discapacidad,
    flag_domiciliado = EXCLUDED.flag_domiciliado,
    flag_comision_afp = EXCLUDED.flag_comision_afp,
    flag_pensionista = EXCLUDED.flag_pensionista,
    flag_afiliado_eps = EXCLUDED.flag_afiliado_eps,
    flag_essalud_vida = EXCLUDED.flag_essalud_vida,
    flag_sctr_pension = EXCLUDED.flag_sctr_pension,
    flag_sctr_salud = EXCLUDED.flag_sctr_salud,
    flag_quinta_exonerado = EXCLUDED.flag_quinta_exonerado,
    distrito_id = EXCLUDED.distrito_id,
    tipo_via_id = EXCLUDED.tipo_via_id,
    nombre_via = EXCLUDED.nombre_via,
    numero_via = EXCLUDED.numero_via,
    tipo_zona_id = EXCLUDED.tipo_zona_id,
    nombre_zona = EXCLUDED.nombre_zona,
    tipo_vivienda_id = EXCLUDED.tipo_vivienda_id,
    interior = EXCLUDED.interior,
    referencia = EXCLUDED.referencia,
    cuenta_bancaria_sueldo = EXCLUDED.cuenta_bancaria_sueldo,
    cuenta_cts = EXCLUDED.cuenta_cts,
    banco_sueldo_id = EXCLUDED.banco_sueldo_id,
    banco_cts_id = EXCLUDED.banco_cts_id,
    moneda_sueldo_id = EXCLUDED.moneda_sueldo_id,
    moneda_cts_id = EXCLUDED.moneda_cts_id,
    admin_afp_id = EXCLUDED.admin_afp_id,
    cuspp = EXCLUDED.cuspp,
    pension_rtps_id = EXCLUDED.pension_rtps_id,
    regimen_pensionario_id = EXCLUDED.regimen_pensionario_id,
    fec_ini_afil_afp = EXCLUDED.fec_ini_afil_afp,
    fec_fin_afil_afp = EXCLUDED.fec_fin_afil_afp,
    regimen_laboral_id = EXCLUDED.regimen_laboral_id,
    tipo_trabajador_id = EXCLUDED.tipo_trabajador_id,
    tipo_trabajador_rtps_id = EXCLUDED.tipo_trabajador_rtps_id,
    ocupacion_rtps_id = EXCLUDED.ocupacion_rtps_id,
    seccion_id = EXCLUDED.seccion_id,
    centro_costo_id = EXCLUDED.centro_costo_id,
    sucursal_id = EXCLUDED.sucursal_id,
    nro_brevete = EXCLUDED.nro_brevete,
    autogenerado_essalud = EXCLUDED.autogenerado_essalud,
    procedencia = EXCLUDED.procedencia,
    comentario = EXCLUDED.comentario,
    porc_judicial = EXCLUDED.porc_judicial,
    porc_jud_util = EXCLUDED.porc_jud_util,
    flag_cat_trab = EXCLUDED.flag_cat_trab,
    flag_dscto_comedor = EXCLUDED.flag_dscto_comedor,
    fecha_ingreso = EXCLUDED.fecha_ingreso,
    fecha_cese = EXCLUDED.fecha_cese,
    motivo_cese_id = EXCLUDED.motivo_cese_id,
    flag_estado = EXCLUDED.flag_estado,
    fec_modificacion = NOW();

COMMIT;
