# Contexto mínimo para ms-rrhh: solo common/ + ms-rrhh/ + pom.xml raíz
# BuildKit (DOCKER_BUILDKIT=1) usa este archivo antes que el .dockerignore global
api-gateway
config-server
ms-activos-fijos
ms-almacen
ms-auditoria
ms-auth-security
ms-compras
ms-contabilidad
ms-core-maestros
ms-finanzas
ms-notificaciones
ms-produccion
ms-reportes
ms-ventas
ms-worker
scripts
config
**/.idea
**/.vscode
**/*.iml
**/target
.git
**/*.log
**/*.tmp
**/.DS_Store
**/Thumbs.db
