import { Observable } from 'rxjs';
import { PermisoEntity } from '../models/permiso.entity';
import { VacacionLicenciaEntity } from '../models/vacacion-licencia.entity';
import { AsistenciaEntity } from '../models/asistencia.entity';
import { CalendarioLaboralEntity } from '../models/calendario-laboral.entity';
import { AnalisisInconsistenciaEntity } from '../models/analisis-inconsistencia.entity';
import { InasistenciaEntity } from '../models/inasistencia.entity';
import { ReportePlanillaEntity } from '../models/reporte-planilla.entity';
import { AfiliacionFondosPensionEntity } from '../models/afiliacion-fondos-pension.entity';
import { PaisVigenciaEntity } from '../models/pais-vigencia.entity';
import { TipoContratoEntity } from '../models/tipo-contrato.entity';
import { PlanillaEntity } from '../models/planilla.entity';
import { ConceptoEntity } from '../models/concepto.entity';
import { ProcesosEspecialesEntity } from '../models/procesos-especiales.entity';
import { ProvisionGastoEntity } from '../models/provision-gasto.entity';
import { LiquidacionEntity } from '../models/liquidacion.entity';
import { DashboardRrhhEntity } from '../models/dashboard-rrhh.entity';
import { DistribucionCostosEntity } from '../models/distribucion-costos.entity';
import { EmisionBoletasEntity } from '../models/emision-boletas.entity';
import { GeneracionArchivosEntity } from '../models/generacion-archivos.entity';
import { IndicadoresRotacionEntity } from '../models/indicadores-rotacion.entity';

export abstract class IReportesRepository {
  abstract obtenerPermisos(): Observable<PermisoEntity[]>;
  abstract obtenerPermisosRegistro(): Observable<PermisoEntity[]>;
  abstract obtenerVacacionesLicencias(): Observable<VacacionLicenciaEntity[]>;
  abstract obtenerVacacionesLicenciasRegistro(): Observable<VacacionLicenciaEntity[]>;
  abstract obtenerAsistencias(): Observable<AsistenciaEntity[]>;
  abstract obtenerCalendariosLaborales(): Observable<CalendarioLaboralEntity[]>;
  abstract obtenerAnalisisInconsistenciaNomina(): Observable<AnalisisInconsistenciaEntity[]>;
  abstract obtenerInasistencias(): Observable<InasistenciaEntity[]>;
  abstract obtenerReportesPlanilla(): Observable<ReportePlanillaEntity[]>;
  abstract obtenerAfiliacionFondosPension(): Observable<AfiliacionFondosPensionEntity[]>;
  abstract obtenerPaisVigencia(): Observable<PaisVigenciaEntity[]>;
  abstract obtenerTipoContrato(): Observable<TipoContratoEntity[]>;
  abstract obtenerAprobarPlanilla(): Observable<PlanillaEntity[]>;
  abstract obtenerCalculoPlanilla(): Observable<PlanillaEntity[]>;
  abstract obtenerConceptos(): Observable<ConceptoEntity[]>;
  abstract obtenerProcesosEspeciales(): Observable<ProcesosEspecialesEntity[]>;
  abstract obtenerProvisionGasto(): Observable<ProvisionGastoEntity[]>;
  abstract obtenerRegistrarLiquidacion(): Observable<LiquidacionEntity[]>;
  abstract obtenerDashboardRrhh(): Observable<DashboardRrhhEntity>;
  abstract obtenerDistribucionCostos(): Observable<DistribucionCostosEntity[]>;
  abstract obtenerEmisionBoletas(): Observable<EmisionBoletasEntity[]>;
  abstract obtenerGeneracionArchivos(): Observable<GeneracionArchivosEntity[]>;
  abstract obtenerIndicadoresRotacion(): Observable<IndicadoresRotacionEntity[]>;
}
