server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native

# Configuración de logging para debug
logging:
  level:
    org.springframework.cloud.config: DEBUG
    com.sigre.config: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://10.100.14.102:8761/eureka
  instance:
    hostname: 10.100.14.102
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator

---
# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
