server:
  port: 9080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/order/**
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/product/**
        - id: asistencia-service
          uri: lb://asistencia-service
          predicates:
            - Path=/api/asistencia/**
          filters:
            - RewritePath=/api/asistencia/(?<segment>.*), /${segment}
        - id: discovery-service
          uri: http://10.100.14.102:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-service-static
          uri: http://10.100.14.102:8761
          predicates:
            - Path=/eureka/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    service-url:
      defaultZone: http://10.100.14.102:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info

---
# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
