# Restaurant.pe ERP — Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'ms-auth-security'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-auth-security:9001']

  - job_name: 'ms-core-maestros'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-core-maestros:9002']

  - job_name: 'ms-almacen'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-almacen:9003']

  - job_name: 'ms-compras'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-compras:9004']

  - job_name: 'ms-finanzas'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-finanzas:9005']

  - job_name: 'ms-contabilidad'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-contabilidad:9006']

  - job_name: 'ms-rrhh'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-rrhh:9007']

  - job_name: 'ms-activos-fijos'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-activos-fijos:9008']

  - job_name: 'ms-produccion'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-produccion:9009']

  - job_name: 'ms-ventas'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-ventas:9010']

  - job_name: 'ms-auditoria'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-auditoria:9011']

  - job_name: 'ms-reportes'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-reportes:9012']

  - job_name: 'ms-notificaciones'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-notificaciones:9013']

  - job_name: 'ms-worker'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ms-worker:9014']
