//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigreWebServiceWrapper.ConsultaRUCService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SunatWebServices/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(beanAncestorWS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(beanPadronRuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SunatWebServices/")]
    public partial class beanAncestor
    {
        
        private bool isOkField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool isOk
        {
            get
            {
                return this.isOkField;
            }
            set
            {
                this.isOkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(beanPadronRuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SunatWebServices/")]
    public partial class beanAncestorWS : beanAncestor
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SunatWebServices/")]
    public partial class beanPadronRuc : beanAncestorWS
    {
        
        private string rucField;
        
        private string razonSocialField;
        
        private string estadoField;
        
        private string condicionField;
        
        private string ubigeoField;
        
        private string tipoViaField;
        
        private string nombreViaField;
        
        private string codigoZonaField;
        
        private string tipoZonaField;
        
        private string numeroField;
        
        private string interiorField;
        
        private string loteField;
        
        private string departamentoField;
        
        private string manzanaField;
        
        private string kilometroField;
        
        private string codProvinciaField;
        
        private string descProvinciaField;
        
        private string codDepartamentoField;
        
        private string descDepartamentoField;
        
        private string descDistritoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ruc
        {
            get
            {
                return this.rucField;
            }
            set
            {
                this.rucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string condicion
        {
            get
            {
                return this.condicionField;
            }
            set
            {
                this.condicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ubigeo
        {
            get
            {
                return this.ubigeoField;
            }
            set
            {
                this.ubigeoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoVia
        {
            get
            {
                return this.tipoViaField;
            }
            set
            {
                this.tipoViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreVia
        {
            get
            {
                return this.nombreViaField;
            }
            set
            {
                this.nombreViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoZona
        {
            get
            {
                return this.codigoZonaField;
            }
            set
            {
                this.codigoZonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoZona
        {
            get
            {
                return this.tipoZonaField;
            }
            set
            {
                this.tipoZonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string interior
        {
            get
            {
                return this.interiorField;
            }
            set
            {
                this.interiorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string lote
        {
            get
            {
                return this.loteField;
            }
            set
            {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string manzana
        {
            get
            {
                return this.manzanaField;
            }
            set
            {
                this.manzanaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string kilometro
        {
            get
            {
                return this.kilometroField;
            }
            set
            {
                this.kilometroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string codProvincia
        {
            get
            {
                return this.codProvinciaField;
            }
            set
            {
                this.codProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string descProvincia
        {
            get
            {
                return this.descProvinciaField;
            }
            set
            {
                this.descProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string codDepartamento
        {
            get
            {
                return this.codDepartamentoField;
            }
            set
            {
                this.codDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string descDepartamento
        {
            get
            {
                return this.descDepartamentoField;
            }
            set
            {
                this.descDepartamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string descDistrito
        {
            get
            {
                return this.descDistritoField;
            }
            set
            {
                this.descDistritoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SunatWebServices/", ConfigurationName="SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC")]
    public interface IFaceConsultaRUC
    {
        
        // CODEGEN: El parámetro "pRucConsulta" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SigreWebServiceWrapper.ConsultaRUCService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(beanAncestor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="BeanPadronRuc")]
        SigreWebServiceWrapper.ConsultaRUCService.consultarResponse consultar(SigreWebServiceWrapper.ConsultaRUCService.consultar request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SigreWebServiceWrapper.ConsultaRUCService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(beanAncestor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SigreWebServiceWrapper.ConsultaRUCService.consultarPBResponse consultarPB(SigreWebServiceWrapper.ConsultaRUCService.consultarPB request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SigreWebServiceWrapper.ConsultaRUCService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(beanAncestor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SigreWebServiceWrapper.ConsultaRUCService.consultarJSONResponse consultarJSON(SigreWebServiceWrapper.ConsultaRUCService.consultarJSON request);
        
        // CODEGEN: El parámetro "return" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SigreWebServiceWrapper.ConsultaRUCService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(beanAncestor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SigreWebServiceWrapper.ConsultaRUCService.testResponse test(SigreWebServiceWrapper.ConsultaRUCService.test request);
        
        // CODEGEN: El parámetro "pRUC" requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es "Microsoft.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SigreWebServiceWrapper.ConsultaRUCService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(beanAncestor))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="BeanPadronRuc")]
        SigreWebServiceWrapper.ConsultaRUCService.getOneResponse getOne(SigreWebServiceWrapper.ConsultaRUCService.getOne request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultar
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pComputerName;
        
        public consultar()
        {
        }
        
        public consultar(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            this.pRucConsulta = pRucConsulta;
            this.pRucOrigen = pRucOrigen;
            this.pUsuario = pUsuario;
            this.pClave = pClave;
            this.pEmpresa = pEmpresa;
            this.pComputerName = pComputerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarResponse", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc BeanPadronRuc;
        
        public consultarResponse()
        {
        }
        
        public consultarResponse(SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc BeanPadronRuc)
        {
            this.BeanPadronRuc = BeanPadronRuc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPB", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultarPB
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pComputerName;
        
        public consultarPB()
        {
        }
        
        public consultarPB(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            this.pRucConsulta = pRucConsulta;
            this.pRucOrigen = pRucOrigen;
            this.pUsuario = pUsuario;
            this.pClave = pClave;
            this.pEmpresa = pEmpresa;
            this.pComputerName = pComputerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarPBResponse", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultarPBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc @return;
        
        public consultarPBResponse()
        {
        }
        
        public consultarPBResponse(SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarJSON", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultarJSON
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucConsulta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRucOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pClave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pComputerName;
        
        public consultarJSON()
        {
        }
        
        public consultarJSON(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            this.pRucConsulta = pRucConsulta;
            this.pRucOrigen = pRucOrigen;
            this.pUsuario = pUsuario;
            this.pClave = pClave;
            this.pEmpresa = pEmpresa;
            this.pComputerName = pComputerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarJSONResponse", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class consultarJSONResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public consultarJSONResponse()
        {
        }
        
        public consultarJSONResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="test", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class test
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRUC;
        
        public test()
        {
        }
        
        public test(string pRUC)
        {
            this.pRUC = pRUC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testResponse", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class testResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public testResponse()
        {
        }
        
        public testResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOne", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class getOne
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pRUC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pClave;
        
        public getOne()
        {
        }
        
        public getOne(string pRUC, string pUsuario, string pClave)
        {
            this.pRUC = pRUC;
            this.pUsuario = pUsuario;
            this.pClave = pClave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOneResponse", WrapperNamespace="http://SunatWebServices/", IsWrapped=true)]
    public partial class getOneResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SunatWebServices/", Order=0)]
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc BeanPadronRuc;
        
        public getOneResponse()
        {
        }
        
        public getOneResponse(SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc BeanPadronRuc)
        {
            this.BeanPadronRuc = BeanPadronRuc;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFaceConsultaRUCChannel : SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FaceConsultaRUCClient : System.ServiceModel.ClientBase<SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC>, SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FaceConsultaRUCClient() : 
                base(FaceConsultaRUCClient.GetDefaultBinding(), FaceConsultaRUCClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ImplConsultaRUCPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FaceConsultaRUCClient(EndpointConfiguration endpointConfiguration) : 
                base(FaceConsultaRUCClient.GetBindingForEndpoint(endpointConfiguration), FaceConsultaRUCClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FaceConsultaRUCClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FaceConsultaRUCClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FaceConsultaRUCClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FaceConsultaRUCClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FaceConsultaRUCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SigreWebServiceWrapper.ConsultaRUCService.consultarResponse SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC.consultar(SigreWebServiceWrapper.ConsultaRUCService.consultar request)
        {
            return base.Channel.consultar(request);
        }
        
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc consultar(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            SigreWebServiceWrapper.ConsultaRUCService.consultar inValue = new SigreWebServiceWrapper.ConsultaRUCService.consultar();
            inValue.pRucConsulta = pRucConsulta;
            inValue.pRucOrigen = pRucOrigen;
            inValue.pUsuario = pUsuario;
            inValue.pClave = pClave;
            inValue.pEmpresa = pEmpresa;
            inValue.pComputerName = pComputerName;
            SigreWebServiceWrapper.ConsultaRUCService.consultarResponse retVal = ((SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC)(this)).consultar(inValue);
            return retVal.BeanPadronRuc;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SigreWebServiceWrapper.ConsultaRUCService.consultarPBResponse SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC.consultarPB(SigreWebServiceWrapper.ConsultaRUCService.consultarPB request)
        {
            return base.Channel.consultarPB(request);
        }
        
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc consultarPB(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            SigreWebServiceWrapper.ConsultaRUCService.consultarPB inValue = new SigreWebServiceWrapper.ConsultaRUCService.consultarPB();
            inValue.pRucConsulta = pRucConsulta;
            inValue.pRucOrigen = pRucOrigen;
            inValue.pUsuario = pUsuario;
            inValue.pClave = pClave;
            inValue.pEmpresa = pEmpresa;
            inValue.pComputerName = pComputerName;
            SigreWebServiceWrapper.ConsultaRUCService.consultarPBResponse retVal = ((SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC)(this)).consultarPB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SigreWebServiceWrapper.ConsultaRUCService.consultarJSONResponse SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC.consultarJSON(SigreWebServiceWrapper.ConsultaRUCService.consultarJSON request)
        {
            return base.Channel.consultarJSON(request);
        }
        
        public string consultarJSON(string pRucConsulta, string pRucOrigen, string pUsuario, string pClave, string pEmpresa, string pComputerName)
        {
            SigreWebServiceWrapper.ConsultaRUCService.consultarJSON inValue = new SigreWebServiceWrapper.ConsultaRUCService.consultarJSON();
            inValue.pRucConsulta = pRucConsulta;
            inValue.pRucOrigen = pRucOrigen;
            inValue.pUsuario = pUsuario;
            inValue.pClave = pClave;
            inValue.pEmpresa = pEmpresa;
            inValue.pComputerName = pComputerName;
            SigreWebServiceWrapper.ConsultaRUCService.consultarJSONResponse retVal = ((SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC)(this)).consultarJSON(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SigreWebServiceWrapper.ConsultaRUCService.testResponse SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC.test(SigreWebServiceWrapper.ConsultaRUCService.test request)
        {
            return base.Channel.test(request);
        }
        
        public string test(string pRUC)
        {
            SigreWebServiceWrapper.ConsultaRUCService.test inValue = new SigreWebServiceWrapper.ConsultaRUCService.test();
            inValue.pRUC = pRUC;
            SigreWebServiceWrapper.ConsultaRUCService.testResponse retVal = ((SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC)(this)).test(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SigreWebServiceWrapper.ConsultaRUCService.getOneResponse SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC.getOne(SigreWebServiceWrapper.ConsultaRUCService.getOne request)
        {
            return base.Channel.getOne(request);
        }
        
        public SigreWebServiceWrapper.ConsultaRUCService.beanPadronRuc getOne(string pRUC, string pUsuario, string pClave)
        {
            SigreWebServiceWrapper.ConsultaRUCService.getOne inValue = new SigreWebServiceWrapper.ConsultaRUCService.getOne();
            inValue.pRUC = pRUC;
            inValue.pUsuario = pUsuario;
            inValue.pClave = pClave;
            SigreWebServiceWrapper.ConsultaRUCService.getOneResponse retVal = ((SigreWebServiceWrapper.ConsultaRUCService.IFaceConsultaRUC)(this)).getOne(inValue);
            return retVal.BeanPadronRuc;
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ImplConsultaRUCPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ImplConsultaRUCPort))
            {
                return new System.ServiceModel.EndpointAddress("http://pegazus.serveftp.com:9080/SunatWebServices/ImplConsultaRUC");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FaceConsultaRUCClient.GetBindingForEndpoint(EndpointConfiguration.ImplConsultaRUCPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FaceConsultaRUCClient.GetEndpointAddress(EndpointConfiguration.ImplConsultaRUCPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ImplConsultaRUCPort,
        }
    }
}
