spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/restaurant_pe_security
    username: restaurant_admin
    password: ""
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: restaurant
    password: R4bb1t_D3v!

app:
  encryption:
    key: UmVzdGF1cmFudFBlQWVzMjU2S2V5RGV2MjAyNiEhISE=
  schema-sync:
    admin-secret: dev-schema-sync
    template-database: restaurant_pe_template
    schedule:
      enabled: false
