spring:
  datasource:
    url: jdbc:postgresql://db-sigre-web:5432/db-sigre-web
    username: sigre-web
    password: S1greW3b@2025!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update  # Mantener update - usuario eliminará tablas manualmente
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  # Configuración de email (EXACTAMENTE igual que sync-service)
  mail:
    host: mail.franevi.com
    port: 26
    username: facturacion.electronica@franevi.com
    password: S1gr3@2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    notifications:
      enabled: true  # Habilitado con estructura robusta del sync-service
      recipients: 
        - jramirez@npssac.com.pe
        - esilva@transmarina.com
      subject: "[SIGRE-ASISTENCIA] Error en Sistema de Asistencia"
    smtp:
      from: facturacion.electronica@franevi.com

# Configuración específica del servicio de asistencia
asistencia:
  config:
    procesamiento:
      async-enabled: true                    # Habilitar procesamiento asíncrono
      max-reintentos: 3                      # Máximo reintentos para tickets con error
      intervalo-procesamiento-segundos: 10   # Intervalo para procesar cola de tickets
    raciones:
      horario-corte-mediodia: 12            # Hora de corte para selección de raciones
      tipos-disponibles:
        - codigo: "ALMUERZO"
          nombre: "Almuerzo"
          disponible-antes-mediodia: true
          disponible-despues-mediodia: false
        - codigo: "CENA" 
          nombre: "Cena"
          disponible-antes-mediodia: true
          disponible-despues-mediodia: true

logging:
  level:
    com.sigre.asistencia: DEBUG
    org.springframework.mail: DEBUG
