spring:
  datasource:
    # Datasource principal para Spring Actuator y health checks
    url: jdbc:postgresql://db-sigre-web:5432/db-sigre-web
    username: sigre-web
    password: S1greW3b@2025!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
    
    # Bases de datos para la aplicación
    local:
      url: jdbc:postgresql://db-sigre-web:5432/db-sigre-web
      username: sigre-web
      password: S1greW3b@2025!
      driver-class-name: org.postgresql.Driver
    
    remote:
      host: 10.100.14.10  # Agregar esta línea
      port: 1522           # Agregar esta línea
      service-name: heimdall  # Agregar esta línea
      username: transmarina
      password: transmarina
      jdbc-url: jdbc:oracle:thin:@//10.100.14.10:1522/heimdall
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:  # Debe estar anidado bajo 'remote'
        maximum-pool-size: 2
        minimum-idle: 0
        connection-timeout: 30000  # 30 segundos es suficiente
        validation-timeout: 5000
        initialization-fail-timeout: -1
        connection-test-query: SELECT 1 FROM DUAL
        auto-commit: false  # <-- CRÍTICO: Agregar esta línea

  jpa:
    show-sql: false
    hibernate:
      # Para PostgreSQL local usamos update para sincronizar columnas de control
      # NOTA: En producción considerar cambiar a 'validate'
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        enable_lazy_load_no_trans: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  # Configuración de email (Servidor SMTP Franevi)
  mail:
    host: mail.franevi.com
    port: 26
    username: facturacion.electronica@franevi.com
    password: S1gr3@2025
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
    notifications:
      enabled: true  # Habilitado con credenciales reales
      recipients: 
        - jramirez@npssac.com.pe
        - esilva@transmarina.com
        - mcarbajal@transmarina.com
      subject: "[SIGRE] Reporte de Sincronización - Módulo de Asistencia"
    smtp:
      from: facturacion.electronica@franevi.com

# Configuración específica del servicio de sincronización
sync:
  config:
    interval-minutes: 5              # Intervalo entre sincronizaciones (configurado a 5 minutos)
    retry-delay-seconds: 30          # Delay antes de reintentar en caso de error
    max-retries: 5                   # Número máximo de reintentos por tabla
    initial-sync-on-startup: true    # Ejecutar sincronización inicial al arranque
    cod-origen: SE                   # Código de origen para filtrar registros de asistencia (debe coincidir con frontend)

logging:
  level:
    com.sigre.sync: DEBUG