version: '3.8'

services:
  sigre-asistencia-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigre-asistencia-frontend
    ports:
      - "9080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - sigre-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sigre-network:
    driver: bridge
