server:
  port: 0

spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Lima
  datasource:
    url: jdbc:postgresql://10.100.14.102:5432/db-sigre-web
    username: sigre-web
    password: S1greW3b@2025!

eureka:
  client:
    service-url:
      defaultZone: http://10.100.14.102:8761/eureka
  instance:
    hostname: 10.100.14.102
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

---
# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db-sigre-web:5432/db-sigre-web

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
