server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://10.100.14.102:8761/eureka
  instance:
    hostname: 10.100.14.102
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sigre.sync: DEBUG
    org.springframework.jdbc: WARN
    org.hibernate.SQL: WARN

---
# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka